create_wed/urls.py
from django.urls import path
from create_wed import views
from create_wed.views import ContactUs

app_name = 'create_wed'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name='home'),
    path('create_wedding/', views.create_weeding_view, name='create_wedding'),
    path('contact/', ContactUs.as_view(), name='contact'),
    path('services/', views.services, name='services'),

]

guests/urls.py
from django.urls import path

from guests import views
from guests.views import ManualGuestListView, UpdateManualGuestListView

app_name = 'guests'
urlpatterns = [
    # path('', views.index, name='index'),
    # path('guests-list/', GuestListView.as_view(), name='guests-list'),
    # path('party-list/', PartyListView.as_view(), name='party-list'),
    path('manual_guest_list/', ManualGuestListView.as_view(), name='manual_guest_list'),
    path('create_manual_guest_list/', UpdateManualGuestListView.as_view(), name='create_manual_guest_list'),
    path('send_email/', views.send_email, name='send_email'),

]

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'
urlpatterns = [
    path('todo_list/', views.index, name='todo_list'),
    path('create_coordination/', views.CreateCoordinationView.as_view(), name='create_coordination'),
    path('update_coordination/', views.UpdateCoordinationView.as_view(), name='update_coordination'),
    path('create_wedding_day/', views.CreateWeddingDayView.as_view(), name='create_wedding_day'),
    path('wedding_day/', views.WeddingDayView.as_view(), name='wedding_day'),
    ]

wedding_planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create_wed/', include('create_wed.urls')),
    path('todo/', include('todo.urls')),
    path('guests/', include('guests.urls')),
]

create_wed/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models

# Create your models here.

GENDER_CHOICES = [
    ('Female', 'Female'),
    ('Male', 'Male'),
]


class Wedding(models.Model):
    wedding_name = models.CharField(max_length=100)
    wedding_date = models.DateField(default=date.today)
    wedding_time = models.TimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    partner1_gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default="", editable=False)
    partner1_email = models.EmailField(max_length=70,blank=True, null=True, unique=True)
    partner2_gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default="", editable=False)
    partner2_email = models.EmailField(max_length=70,blank=True, null=True, unique=True)


    def __str__(self):
        return f'{self.wedding_name} {self.user}'


class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=70, blank=True, null=True)
    message = models.CharField(max_length=1000)

create_wed/forms.py
from django.forms import Form, CharField, EmailField, PasswordInput, TextInput, EmailInput, ChoiceField, RadioSelect, \
    DateField, DateInput, TimeField, TimeInput, ModelForm

from create_wed.models import ContactUs


class SignUpForm(Form):
    username = CharField(widget=TextInput(attrs={
        'class': 'form-control w-75'
    }))
    password = CharField(widget=PasswordInput(attrs={
        'class': 'form-control w-75'
    }))
    email = EmailField(label='Email', widget=EmailInput(attrs={
        'class': 'form-control w-75'
    }))
    first_name = CharField(label='First Name', widget=TextInput(attrs={
        'class': 'form-control w-75'
    }))
    last_name = CharField(label='Last Name', widget=TextInput(attrs={
        'class': 'form-control w-75'
    }))



class LoginForm(Form):
    username = CharField(widget=TextInput(attrs={
        'class': 'form-control w-75'
    }))
    password = CharField(widget=PasswordInput(attrs={
        'class': 'form-control w-75'
    }))


GENDER_CHOICES = [
    ('Female', 'Female'),
    ('Male', 'Male'),
]


class CreateWeddingForm(Form):
    partner1_gender = ChoiceField(label='Personal', required=True, widget=RadioSelect(
                    attrs={'class': 'Radio'}), choices=(GENDER_CHOICES))
    partner1_email = EmailField(label='Email', widget=EmailInput(attrs={
        'class': 'form-control w-75'}))
    partner2_gender = ChoiceField(label='Partner', required=True, widget=RadioSelect(
                    attrs={'class': 'Radio'}), choices=(GENDER_CHOICES))
    partner2_email =EmailField(label='Email', widget=EmailInput(attrs={
        'class': 'form-control w-75'}))
    wedding_name = CharField(label='Wedding Name', widget=TextInput(attrs={
        'class': 'form-control w-75'}))
    wedding_date = DateField(label='Wedding Date', widget=DateInput(format="%m/%d/%Y"),initial='MM/DD/YYYY')
    wedding_time = TimeField(label='Wedding Time', widget=TimeInput(format='%H:%M'))


class ContactUsForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = '__all__'
        widgets = {
            'name': TextInput(attrs={'class': 'form-control w-75'}),
            'email': TextInput(attrs={'class': 'form-control w-75'}),
            'message': TextInput(attrs={'class': 'form-control w-75'}),
        }

create_wed/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import CreateView


from create_wed.forms import SignUpForm, LoginForm, CreateWeddingForm, ContactUsForm

# Create your views here.
from create_wed.models import Wedding


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                messages.warning(request, f"{form.cleaned_data['username']} is already in use")
                return redirect(reverse('signup'))
            user = User.objects.create_user(**form.cleaned_data)
            messages.info(request, f'{user.username} successfully created!')
            return redirect(reverse('create_wed/login'))
    else:
        form = SignUpForm()

    return render(request, 'create_wed/signup.html', {'form': form})

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(request, **form.cleaned_data)
            if user:
                login(request, user)
                messages.info(request, 'Successfully logged in!')
                return redirect(reverse('create_wed:home'))
            else:
                messages.error(request, 'Bad authentication...')
                return redirect(reverse('create_wed:login'))
    else:
        form = LoginForm()

    return render(request, 'create_wed/login.html', {'form': form})

def logout_view(request):
    logout(request)
    messages.info(request, 'Logged out')
    return redirect(reverse('create_wed:home'))

# @login_required
def home(request):
    return render(request, 'create_wed/index.html')


@login_required
def create_weeding_view(request):
    if request.method == 'POST':
        form = CreateWeddingForm(request.POST)
        print(form.errors)
        if form.is_valid():
            wedding = Wedding(user=request.user,**form.cleaned_data)
            wedding.save()
            messages.info(request, 'Wedding successfully created!')
            return redirect(reverse('create_wed:services'))
    else:
        form = CreateWeddingForm()

    return render(request, 'create_wed/create_wedding.html', {'form': form})


def services(request):
    return render(request, 'create_wed/services.html')


class ContactUs(CreateView):
    form_class = ContactUsForm
    template_name = 'create_wed/contact.html'
    success_url = '/create_wed/home'

templates/create_wed/contact.html
{% extends 'base.html' %}

{% block navbar%}
{% include 'partials/navbar.html' %}
{% endblock %}


{% block content %}

<!-- Services -->
<style>
    .agile-top{
    background-color: #212121 !important;
    z-index: 999;
    width: 100%;
	top: 0%;
	}
    .new_button{
    font-size: 1.1em;
    outline: none;
    border: none;
    text-transform: uppercase;
    background: #000;
    padding: 0.7em 0;
    letter-spacing: 1px;
    color: #fff;
    display: block;
    width: 18%;
    margin: 1.5em auto 0;
    -webkit-transition: .5s all;
    }
</style>

<!-- Contact -->
<div class="contact" id="contact">
    <div class="container" style="margin-top: 100px;">
        <h3 class="w3_tittle">Contact Us</h3>
        <div class="contact-grid1">
            <div class="contact-top1">
                <form action="#" method="post">
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                     <button type="submit" class="new_button">Send</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- //Contact -->

<!-- map -->
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d2482.432383990807!2d0.028213999961443994!3d51.52362882484525!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1423469959819" ></iframe>
    <div class="map-pos">
        <h3>ADDRESS</h3>
        <p>35, Ahad Haam Str.</p>
        <p>Tel Aviv</p>
        <p>Call : 123 456 7890</p>
        <p><a href="mailto:info@example.com">mail@example.com</a></p>
    </div>
</div>
<!-- //map -->


{% endblock %}


{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/create_wed/create_wedding.html
{% extends 'base.html' %}

{% block navbar %}
{% include 'partials/navbar.html' %}
{% endblock %}

{% load static %}

{% block content %}
<style>
    .agile-top{
    background-color: #212121 !important;
    z-index: 999;
    width: 100%;
	top: 0%;
	}
	 .new_button{
            font-size: 1.1em;
            outline: none;
            border: none;
            text-transform: uppercase;
            background: #000;
            padding: 0.7em 0;
            letter-spacing: 1px;
            color: #fff;
            display: block;
            width: 33%;

            -webkit-transition: .5s all;
        }

</style>
<div class="container">
<!-- Create a Wedding -->
<div class="content-agileits" id="about">
    <div class="welcome-w3">
        <div class="container" style="margin-top: 0px">
            <h3 class="w3_tittle">Create a Wedding</h3>
            <div class="welcome-grids">
                <div class="col-md-5 wel-grid1">
                    <div class="port-7 effect-2">
                        <div class="image-box">
                            <img src="{% static 'images/ab.jpg' %}">
                        </div>

                    </div>
                </div>
                <div class="col-md-7 wel-grid">
                    <h4>Pease fill the form below</h4>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <button type="submit" class="new_button" >Create a Wedding</button>
                    </form>
                    </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- //Create a wedding -->

{% endblock %}


{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/create_wed/index.html
{% extends 'base.html' %}

{% load static %}

{% block navbar%}
{% include 'partials/navbar.html' %}
{% endblock %}

<style>
    .counter_image {
    margin-left: -130px;
    margin-bottom: 60px;
    margin-top: 68px;
}
</style>

{% block content %}
<div class="Main-agile">
    <!-- banner -->
 <!-- banner-text -->
    <div class="slider">
        <div class="callbacks_container">
            <ul class="rslides callbacks callbacks1" id="slider4">
                <li>
                    <div class="w3layouts-banner-top banner">
                        <div class="w3l-overlay">
                            <div class="container">
                                <div class="agileits-banner-info">
                                    <h4>Love Is In The Air</h4>
                                    <h3>Initial consultation</h3>
                                    <p>Plan With Us The Wedding Of Your Dreams</p>
                                    {% if user.is_authenticated %}
                                    <h5><a href="{% url 'create_wed:create_wedding' %}" class="view rew3"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>Start Here</a></h5>
                                    {% else %}
                                    <h5><a href="{% url 'create_wed:login' %}" class="view rew3"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>Start Here</a></h5>
                                    {% endif %}</div>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="w3layouts-banner-top banner-2">
                        <div class="w3l-overlay">
                            <div class="container">
                                <div class="agileits-banner-info">
                                    <h4>Love Is In The Air</h4>
                                    <h3>Initial consultation</h3>
                                    <p>Plan With Us The Wedding Of Your Dreams</p>
                                    {% if user.is_authenticated %}
                                    <h5><a href="{% url 'create_wed:create_wedding' %}" class="view rew3"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>Start Here</a></h5>
                                    {% else %}
                                    <h5><a href="{% url 'create_wed:login' %}" class="view rew3" data-toggle="modal" data-target="#myModal5"><span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>Start Here</a></h5>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="clearfix"> </div>
        <!-- //banner-text -->
    </div>
</div>
<!-- //banner -->

<!-- Counter -->
    <section class="counter" style="margin: 60px 0px 44px -50px;">

<h3 class="w3_tittle">Soon!</h3>
                    <img class="counter_image" src="{% static 'images/counter.png' %}" alt="Counter Background">


    </section>
<!-- //Counter -->
<!-- Services -->
<div class="clearfix"> </div>
<div class="agile-serv">
      <div class="container">
          <h3 class="w3_tittle">Our Services</h3>
    <div class="col-md-6 agileits-serv">
        <div class="left-w3l">
            <h4>Wedding Planning Has Never Been Easier</h4>
            <h5>Wedding Planning</h5>
            <p>Planning a wedding involves endless details, deadlines, family drama, and far too often enough stress to
                make you want to just elope. Use our planning checklist, read our budgeting tips, and access our wedding
                planner to help you pull it all together.</p>
            <ul>
                <li><a href="{% url 'guests:manual_guest_list' %}"><i class="glyphicon glyphicon-ok"></i>Start entering guest list </a></li>
                <li><a href="{% url 'todo:create_wedding_day' %}"><i class="glyphicon glyphicon-ok"></i>Wedding Day Schedule</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-ok"></i>Budget planning & tracking estimates</a></li>
            </ul>
        </div>
    </div>
    <div class="col-md-6 right-w3l" style="padding-bottom: 42px;">
        <div class="welcome-bottom">
            <div class="welcome-grid">
                <i class="fa fa-birthday-cake" aria-hidden="true"></i>
                <h4>The Knot</h4>
                <p><a href="{% url 'create_wed:create_wedding' %}">Create your wedding here.</a></p>
            </div>
            <div class="welcome-grid">
                <i class="fa fa-gratipay" aria-hidden="true"></i>
                <h4>To Do</h4>
                <p><a href="{% url 'todo:todo_list' %}">Wedding planning to do list.</a></p>
            </div>
            <div class="welcome-grid">
                <i class="fa fa-glass" aria-hidden="true"></i>
                <h4>Coordination</h4>
                <p><a href="{% url 'todo:create_coordination' %}">List roles that can be done by friends or professionals.</a></p>
            </div>
        </div>
    </div>
    <div class="clearfix"> </div>
</div>
</div>
<!-- //Services -->
<!-- Contact -->
<div class="contact" id="contact">
    <div class="container">
        <h3 class="w3_tittle">Contact Us</h3>
        <div class="contact-grid1">
            <div class="contact-top1">
                <form action="#" method="post">
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="Name" placeholder="Name" required="">
                    </div>
                    <div class="form-group">
                        <label>E-mail</label>
                        <input type="email" name="E-mail" placeholder="E-mail" required="">
                    </div>
                    <div class="form-group">
                        <label>Message</label>
                        <textarea placeholder name="Message" required=""></textarea>
                    </div>
                    <input type="submit" value="Send">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- //Contact -->
<!-- map -->
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d2482.432383990807!2d0.028213999961443994!3d51.52362882484525!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1423469959819" ></iframe>
    <div class="map-pos">
        <h3>ADDRESS</h3>
        <p>35, Ahad Haam Str.</p>
        <p>Tel Aviv</p>
        <p>Call : 123 456 7890</p>
        <p><a href="mailto:info@example.com">mail@example.com</a></p>
    </div>
</div>
<!-- //map -->
<!-- //main -->

{% endblock %}

<style>
    .counter_image {
    margin-left: -130px;
    margin-bottom: 60px;
    margin-top: 68px;
}
</style>

{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/create_wed/login.html
{% extends 'base.html' %}

{% block navbar%}
{% include 'partials/navbar.html' %}
{% endblock %}


{% block content %}

<!-- Services -->
<style>
    .agile-top{
    background-color: #212121 !important;
    z-index: 999;
    width: 100%;
	top: 0%;
	}
    .new_button{
    font-size: 1.1em;
    outline: none;
    border: none;
    text-transform: uppercase;
    background: #000;
    padding: 0.7em 0;
    letter-spacing: 1px;
    color: #fff;
    display: block;
    width: 18%;
    margin: 1.5em auto 0;
    -webkit-transition: .5s all;
    }
</style>

<div class="contact" id="contact">
    <div class="container" style="margin-top: 100px;">
        <h3 class="w3_tittle">Login To Your Perfect Wedding</h3>
        <div class="contact-grid1">
            <div class="contact-top1">
                <form action="#" method="post">
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                     <button type="submit" class="new_button">Login</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/create_wed/services.html
{% extends 'base.html' %}

{% block navbar%}
{% include 'partials/navbar.html' %}
{% endblock %}


{% block content %}

<!-- Services -->
<style>
    .agile-top{
    background-color: #212121 !important;
    z-index: 999;
    width: 100%;
	top: 0%;
	}

</style>

<div class="clearfix"> </div>
<div class="agile-serv">
      <div class="container" style="margin-top: 50px;">
          <h3 class="w3_tittle">Our Services</h3>
    <div class="col-md-6 agileits-serv">
        <div class="left-w3l">
            <h4>Wedding Planning Has Never Been Easier</h4>
            <h5>Wedding Planning</h5>
            <p>Planning a wedding involves endless details, deadlines, family drama, and far too often enough stress to
                make you want to just elope. Use our planning checklist, read our budgeting tips, and access our wedding
                planner to help you pull it all together.</p>
            <ul>
                <li><a href="{% url 'guests:manual_guest_list' %}"><i class="glyphicon glyphicon-ok"></i>Start entering guest list </a></li>
                <li><a href="{% url 'todo:create_wedding_day' %}"><i class="glyphicon glyphicon-ok"></i>Wedding Day Schedule</a></li>
                <li><a href="{% url 'guests:send_email' %}"><i class="glyphicon glyphicon-ok"></i>Save the Date & Invitations emails</a></li>
            </ul>
        </div>
    </div>
    <div class="col-md-6 right-w3l" style="padding-bottom: 42px;">
        <div class="welcome-bottom">
            <div class="welcome-grid">
                <i class="fa fa-birthday-cake" aria-hidden="true"></i>
                <h4>The Knot</h4>
                <p><a href="{% url 'create_wed:create_wedding' %}">Create your wedding here.</a></p>
            </div>
            <div class="welcome-grid">
                <i class="fa fa-gratipay" aria-hidden="true"></i>
                <h4>To Do</h4>
                <p><a href="{% url 'todo:todo_list' %}">Wedding planning to do list.</a></p>
            </div>
            <div class="welcome-grid">
                <i class="fa fa-glass" aria-hidden="true"></i>
                <h4>Coordination</h4>
                <p><a href="{% url 'todo:create_coordination' %}">List roles that can be done by friends or professionals.</a></p>
            </div>
        </div>
    </div>
    <div class="clearfix"> </div>
</div>
</div>


<!-- //Services -->

{% endblock %}


{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}

templates/create_wed/signup.html
{% extends 'base.html' %}

{% block navbar%}
{% include 'partials/navbar.html' %}
{% endblock %}


{% block content %}

<!-- Services -->
<style>
    .agile-top{
    background-color: #212121 !important;
    z-index: 999;
    width: 100%;
	top: 0%;
	}
    .new_button{
    font-size: 1.1em;
    outline: none;
    border: none;
    text-transform: uppercase;
    background: #000;
    padding: 0.7em 0;
    letter-spacing: 1px;
    color: #fff;
    display: block;
    width: 18%;
    margin: 1.5em auto 0;
    -webkit-transition: .5s all;
    }
</style>

<div class="contact" id="contact">
    <div class="container" style="margin-top: 100px;">
        <h3 class="w3_tittle">Registration</h3>
        <div class="contact-grid1">
            <div class="contact-top1">
                <form action="#" method="post">
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                     <button type="submit" class="new_button">SignUp</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block footer %}
{% include 'partials/footer.html' %}
{% endblock %}