create_wed/urls.py
from django.urls import path
from create_wed import views
from create_wed.views import ContactUs

app_name = 'create_wed'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home, name='home'),
    path('create_wedding/', views.create_weeding_view, name='create_wedding'),
    path('contact/', ContactUs.as_view(), name='contact'),
    path('services/', views.services, name='services'),

]

todo/urls.py
from django.urls import path
from todo import views

app_name = 'todo'
urlpatterns = [
    path('todo_list/', views.index, name='todo_list'),
    path('create_coordination/', views.CreateCoordinationView.as_view(), name='create_coordination'),
    path('update_coordination/', views.UpdateCoordinationView.as_view(), name='update_coordination'),
    path('create_wedding_day/', views.CreateWeddingDayView.as_view(), name='create_wedding_day'),
    path('wedding_day/', views.WeddingDayView.as_view(), name='wedding_day'),
    ]

wedding_planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('create_wed/', include('create_wed.urls')),
    path('todo/', include('todo.urls')),
    path('guests/', include('guests.urls')),
]

templates/partials/footer.html
<!-- Footer -->
<div class="footer w3ls" style="margin-top: -110px; margin-bottom: -50px;">
	<div class="container">
			<div class="logo-fo">
				<h2><a href="{% url 'create_wed:home' %}">Your Perfect Wedding</a></h2>
			</div>
			<div class="ftr-menu">
				 <ul>
					<li><a href="{% url 'create_wed:home' %}">Home</a></li>
					 {% if user.is_authenticated %}
					 <li><a href="{% url 'create_wed:create_wedding' %}">Create a Wedding</a></li>
					 {% else %}
					 <li><a href="{% url 'create_wed:signup' %}">Registration</a></li>

					 {% endif %}
					<li><a href="{% url 'create_wed:contact' %}">Contact Us</a></li>
					<li><a href="{% url 'create_wed:services' %}">Services</a></li>
				 </ul>
			</div>
			<div class="w3ls-social-icons-2">
				<a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
				<a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
				<a class="pinterest" href="#"><i class="fa fa-google-plus"></i></a>
				<a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
				<a class="tumblr" href="#"><i class="fa fa-tumblr"></i></a>
			</div>
			<div class="clearfix"> </div>
	</div>
</div>

<!-- //Footer -->

templates/partials/navbar.html
    <!--navbar-->
	<div class="agile-top">


		<div class="clearfix"></div>

		<div class="sub-agile">
			<div class="col-md-6 logo">
				<h1><a href="{% url 'create_wed:home' %}">Your Perfect Wedding</a></h1>
			</div>
			<div class="col-md-6 nav-w3l">
			<!-- navigation -->

				<div class="header-right">
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav navbar-left">
							  {% if user.is_authenticated %}
							<li class="active"><a href="{% url 'create_wed:home' %}">HOME</a></li>
							<li><a href="{% url 'create_wed:create_wedding' %}">CREATE A WEDDING</a></li>
							<li><a href="{% url 'create_wed:services' %}">SERVICES</a></li>
							<li><a href="{% url 'create_wed:logout' %}">LOGOUT</a></li>
							{% else %}
							<li class="active"><a href="{% url 'create_wed:home' %}">HOME</a></li>
							<li><a href="{% url 'create_wed:login' %}">LOGIN</a></li>
							<li><a href="{% url 'create_wed:signup' %}">SIGN UP</a></li>
							<li><a href="{% url 'create_wed:contact' %}">CONTACT US</a></li>
							{% endif %}
						</ul>
						<div class="clearfix"> </div>
					</div><!-- //navigation -->
			</div>
		</div>
		<div class="clearfix"> </div>
		</div>
		<div class="clearfix"> </div>
	</div>
    <!-- //navbar -->